# -*- coding: utf-8 -*-
"""Oğuztaşdemir_ödev3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mcFLgnR_0Z7P-UrXARhGHALorclzVt_i

1) Aşağıdaki özelliklere sahip fonksiyonu yazın.

  - "extraction" isimli fonksiyonun "num1" ve "num2" şeklinde argümanları olsun.
  - Bu fonksiyon aldığı parametrelerin farkının mutlak değerini döndürsün.

Not: Mutlak değer için abs() fonksiyonunu kullanabilirsiniz.

  - Parametrelerinizi input() fonksiyonu ile alın ve float'a çevirin. Bu parametrelerle fonk-
  siyonunuzu çağırın.
"""

def extraction(num1,num2):
  fark = num1-num2
  print("Terimlerin farkı: ",abs(fark))

num1 = int(input("Lütfen bir sayı giriniz: "))
num2 = int(input("Lütfen bir sayı giriniz: "))

extraction(num1,num2)

"""2) Aşağıdaki alışveriş listesinin tüm elemanlarını "alt alta" ekrana bastırın. 


shopping_list = ["milk", "oil", "bread", "water", "cucumber", "book"]

  
  Not: Bunu yaparken for döngüsü kullanmanızı bekliyoruz. Slaytlardaki örnekleri inceleyebilirsiniz.
  Eğer tam çıktı alamazsanız indexlere tek tek erişerek de ekrana bastırabilirsiniz.



"""

shopping_list = ["milk", "oil", "bread", "water", "cucumber", "book"]

for i in shopping_list:
  print(i)

"""3) numbers = [23,446,5,76,1,9,76,554,13,26,8,1,97,65,32,1,75]


 Yukarıdaki listenin eleman sayılarının:

    - toplamını,
    - 1 sayısının listede kaç tane olduğunu,
    - en büyük ve en küçük sayının farkını ekrana bastırın.
    - 8 ve 139 sayısının listede olup olmadığını sorgulayın.
    

Listenin tüm elemanlarını "yan yana" ekrana bastırın. print() ile bastırırken alt alta olacak. Soru  çözümlerinde yan yana ekrana bastırmıştık. Dokümandan yararlanabilirsiniz.


"""

numbers = [23,446,5,76,1,9,76,554,13,26,8,1,97,65,32,1,75]
sayaç = 0
bir_sayi = 0

#Elemanların toplamı için
for toplam in numbers: 
  sayaç += toplam 
print("Listedeki tüm elemanların toplamı: ", sayaç)
#print(sum(numbers)) daha pratik yol

#Bir elemanının kaç tane bulunduğunu göstermek için
for bir in numbers:
  if bir == 1:
    bir_sayi += 1
  else:
    continue
print("1 sayısı listede {} tane vardır.".format(bir_sayi))
#print(numbers.count(1)) daha pratik yol


#max ve min değerlerin farkı için
x = min(numbers)
y = max(numbers)
print("Listenin en küçük ve büyük sayıların farkı: ",(y-x))
#print(max(numbers)-min(numbers)) daha pratik yol

#8 ya da 139 sayıları için
for sayi in numbers:
  if sayi == 8 or sayi == 139:
    print("Listede {} elemanı bulunmaktadır.".format(sayi))
# if 8 or 13 in 139: ardından print daha pratik yol

"""4) for number in range():
    # Kodunuzu buraya yazın.

Yukarıdaki döngüyü number 1'den 79'a kadar 3'er 3'er artan sayı listesinin toplamı olacak şekilde tamamlayın. 

Açıklama kısmı: Aşağıdaki döngüyü number 1'den 10'a kadar olan sayıların toplamı olacak şekilde tamamlayın.

for number in range(10):
    
    # Kodunuzu buraya yazın.

"""

for liste in range(1):
  toplam = 0
  for deger in range(1,79,3): #eğer 79 dahilse 79 yerine 80 yazılacak.
    toplam += deger
print("Terimlerin toplamı: ", toplam)

"""5) n_list = [[1,2,3], 4,5,6,7,8,9]

Yukarıdaki listede 2, 3 ve 7 sayılarını ekrana bastırın.

"""

n_list = [[1,2,3], 4,5,6,7,8,9]

#genel liste için
for i in n_list:
  if i == 2 or i == 3 or i == 7:
    print(i)
  else:
    continue

#1. elemanındaki liste için    
  for x in n_list[0]:
    if x == 2 or x == 3 or x == 7:
      print(x)
    else:
      continue