# -*- coding: utf-8 -*-
"""OğuzTaşdemir_ödev5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qlBf5pNK0cBHF4o9EYO9eT5WWt2QT4qK

Sırayla 3 input almak ilk sayı ikinci sayı ve 3. operatör(+,-,*,/) alan bir hesap makinesi yapmak ve olabildiğince alınacak hatalardan kaçmak. tabiki bütün kodu try except içine almak yok mantıklı bir şekilde olası hataları mantıklı şekilde kapatıcaksınız
bu ödevin tek bir cevabı yok ama en az iki hatayı düzeltmeniz gerekiyor (ilk iki değere sayı dışında birşey girilmesi yada 0 ile bölme yapılması)
"""

try:
  a = int(input("Sayı1: "))
  b = int(input("Sayı2: "))
  c = int(input("+ için 1\n - için 2\n * için 3\n / için 4"))
  if c == 1:
    print(a+b)
  elif c == 2:
    print(a-b)
  elif c == 3:
    print(a*b)
  elif c == 4:
    print(a/b)
except ValueError:
  print("Lütfen sayı girin.")
except ZeroDivisionError:
  print("Bir sayı 0'a bölünemez.")